version: "3"
services:
  gke-solati-deployment:
    build: .
    command: npm run start
    volumes:
      - .:/usr/src/node/
      - /usr/src/node/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
  database:
    image: "postgres"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - database-datas:/var/lib/postgresql/data/
volumes:
  database-datas:
