version: "3"
services:
  database:
    container_name: database
    image: "postgres:10"
    ports:
      - "5431:5432"
    env_file:
      - .env-example
    volumes:
      - database-datas4:/var/lib/postgresql/data/
    networks:
      - ws-autenticacion_servicios
  gke-solati-deployment:
    build:
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - database
    volumes:
      - .:/usr/src/node/
      - /usr/src/node/node_modules
    ports:
      - "3000:3000"
    env_file:
      - .env
    networks:
      - ws-autenticacion_servicios
networks:
  ws-autenticacion_servicios:
    external: true
volumes:
  database-datas4:
