version: "3"
services:
  database:
    container_name: database
    image: "postgres:10"
    ports:
      - "5431:5432"
    env_file:
      - .env
    volumes:
      - database-datas4:/var/lib/postgresql/data/
volumes:
  database-datas4:
