apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: monitoreo-api-hpa
  namespace: default
  labels:
    app: monitoreo-api
spec:
  scaleTargetRef:
    kind: Deployment
    name: monitoreo-api
    apiVersion: apps/v1beta1
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: 80
