apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: default
data:
  postgres_user: root
  postgres_password: root
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim2
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres3
spec:
  template:
    metadata:
      labels:
        app: postgres3
    spec:
      volumes:
        - name: postgres-storage2
          persistentVolumeClaim:
            claimName: postgres-pv-claim2
      containers:
        - image: postgres:10
          name: postgres3
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          ports:
            - containerPort: 5432
              name: postgres3
          volumeMounts:
            - name: postgres-storage2
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres3
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: postgres3
